### ISSUE TITLE
Workflow for AMRs with attached manipulators

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rmf_core#110]
I understand that the dispenser workcell is assumed to be some fixed automation equipment that is meant to be shared among multiple AMRs.
For AMRs with attached manipulators (e.g. robot arm), I assume it would be quite different from the current workflow.  For one, the AGV and dispenser are tied together so it's not possible to specify the `pickup_dispenser` and `dropoff_dispenser` in the `Delivery.msg` during task creation as that would depend on agv that gets assigned the task.

Is there any recommendations / tentative workflow for this situation?

What I currently have in mind is to just place a dummy `pickup_dispenser` and `dropoff_dispenser` such that all `DispenserRequest` get routed to the same "dispenser workcell adapter" and manually communicate with the fleet driver to find out which AGV is at the station and actuate the manipulator on that AGV.

**Comment by mxgrey** [comment]
I think all of the current request messages have a significant abstraction problem:

1. They're too low-level to be a good interface for task requests, because requesters really don't care about details like what the pickup waypoint is or what dispensers should be used.
2. They're too high-level to be a good interface for a complete task description, because like you're saying there are all sorts of edge cases that aren't adequately captured.

I think the current delivery task message exists the way it is because we don't have a proper task planning framework yet. At OSRC we've been extremely focused on getting the traffic planning and negotiation right that we haven't had time to really dig into task planning and negotiation.

What I would propose for the long-term is that request messages (like the delivery message) should only include fields that describe the desired outcome (e.g. deliver `x` item(s) to `y` locations) and not include any details about how it should be done. That request should be sent to a distributed task planning + task negotiation system that can gather information about what resources are available and how the task might be accomplished. That task planning system can then issue more detailed lower-level messages to command specific plans based on implementation details of how the robot subsystems work.

However, what I've described will definitely take time. There is still a lot of work that I intend to do on just the traffic planning and negotiation, so I don't have any timeline in mind yet for the task planning and negotiation.

In the meantime, I am fully on board with using dummy values as a stopgap measure. The most important thing is that the fleet adapter needs to know which "dispenser" result to listen to when deciding whether it can proceed to the next phase of its current task. That's all that the `pickup_dispenser` and `dropoff_dispenser` fields are currently being used for.

**Comment by mxgrey** [comment]
One way we could make the stopgap approach work is the following:

In the latest API of the fleet adapter, there's a function called [`FleetUpdateHandle::accept_delivery_request`](https://github.com/osrf/rmf_core/blob/48e98e6dfd8b3d9f224af9394af2befffb8a84a4/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/FleetUpdateHandle.hpp#L85). The fleet adapter developer is expected to pass this function a callback that [takes in a request message and passes back a bool](https://github.com/osrf/rmf_core/blob/48e98e6dfd8b3d9f224af9394af2befffb8a84a4/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/FleetUpdateHandle.hpp#L74-L75).

One thing we could do is have the callback function take in a mutable reference instead of a const-reference, and then you could have your callback modify the `pickup_dispenser` and `dropoff_dispenser` fields before the message gets used by the fleet adapter.

Let me know if that sounds like a desirable approach, and then I can simply remove the `const` on that callback function signature.

**Comment by rcywongaa** [comment]
I don't think modifying the request message is necessary for the time being, since in our case, we know before hand (when creating the delivery request), that we will be using our AGV with attached arm, so we can set the `pickup_dispenser` and `dropoff_dispenser` correctly when creating the delivery request.

On the other hand, I think it might be useful if the `DispenserRequest` message carried some information regarding which AGV the dispenser is to pick from / place to, e.g. a `transporter_name` in addition to the `transporter_type` in the `DispenserRequest`.  I believe it would be useful beyond my stopgap approach.

**Comment by mxgrey** [comment]
Discussing a revision of the `DispenserRequest` message definition might belong in its own thread, but could you elaborate on the use of a `transporter_name` field? Is the idea that if we're delivering to a patient, then we'll want something like:

```
transporter_type: "patient"
transporter_name: <ID of patient>
```

**Comment by rcywongaa** [comment]
I may have misunderstood the use of `transporter_type`.  My understanding is it gets filled with the fleet name, in which case I think it would be useful to also include which AGV in the fleet is handling this task.

e.g.

```
transporter_type: "magni"
transporter_name: "magni001"
```

**Comment by mxgrey** [comment]
The idea is that two robots of the same transporter type should be interacted with in the same way. A `transporter_name` field was intentionally left out of the message definition because of the belief that a dispenser shouldn't have to care about which specific transporter it's interacting with, as long as it knows what type of transporter it is.

**Comment by rcywongaa** [comment]
On second thought, I think your initial idea would make more sense.  I suppose the workflow would be upon receiving call for `accept_delivery_request`, after the delivery has been created and the underlying fleet manager has assigned an AGV, the `FleetUpdateHandle` will use this information to update the relevant `_dispenser` fields with the assigned AGV info.

However, this means that `accept_delivery_request` will need to wait until an AGV is assigned before returning.

In any case, I think removing the `const` on the callback function signature is a way forward.

**Comment by rcywongaa** [comment]
On second thought, I think your proposal of having `accept_delivery_request` modify the `_dispenser` fields would make more sense.

I suppose the workflow would be on receiving call to `accept_delivery_request`, the delivery request is passed to the underlying fleet manager.  When the fleet manager has assigned an AGV, the `FleetUpdateHandle` will update the `_dispenser` fields with the relevant AGV info, which will then be available in the `DispenserRequest` message.

This will, however, mean that `accept_delivery_request` can only return after an AGV has been assigned by the underlying fleet manager.

In any case, I think removing the `const` from the `accept_delivery_request` signature is a way forward.

**Comment by mxgrey** [comment]
In the current implementation of the `full_control` fleet adapter, the fleet adapter is deciding which AGV to assign to the task rather than the fleet manager.

We could add a function to the fleet adapter library's API that accepts a callback where the callback gets told which AGV is assigned, and the callback can modify the fields of the delivery request based on which AGV was chosen.

**Comment by rcywongaa** [comment]
I think that's a good approach

**Comment by rcywongaa** [comment]
Even if the fleet adapter decides which AGV to assign, this only happens when the fleet adapter sends a `follow_new_path` request.  The `_dispenser` field cannot be populated during the `accept_delivery_request`.

So another option forward that maintains the fleet adapter's ability to decide which AGV to assign is to provide the candidate AGV when calling `accept_delivery_request`.

I'm not sure which is a better approach.

**Comment by mxgrey** [comment]
> Even if the fleet adapter decides which AGV to assign, this only happens when the fleet adapter sends a follow_new_path request.

What I meant to suggest in my last post is that we could add a function to the `agv::FleetUpdateHandle` API that lets you give it a callback that will be triggered after the fleet adapter selects an AGV but before it triggers the `follow_new_path` function. That callback will be told which AGV has been selected and it will provide a mutable reference to the delivery request so you can modify its field accordingly.

> So another option forward that maintains the fleet adapter's ability to decide which AGV to assign is to provide the candidate AGV when calling accept_delivery_request.

This wouldn't be ideal because the `accept_delivery_request` gets triggered before an AGV is selected. I would rather not have the fleet adapter waste effort on selecting an optimal AGV for a task if we aren't going to accept the task anyway.

**Comment by rcywongaa** [comment]
I see, that would work also

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
