### ISSUE TITLE
Single pickup multiple dropoff workflow

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rmf_core#134]
It seems the current [`Delivery`](https://github.com/osrf/rmf_core/blob/master/rmf_task_msgs/msg/Delivery.msg) message only supports single pickup single dropoff (location-wise) workflow.

Are there plans for extending this to support single pickup multiple dropoff (e.g. an AGV with multiple compartments which are all loaded at the same location but unloaded at different locations)?

**Comment by mxgrey** [comment]
I think it makes a lot of sense to support delivery requests that can contain `N` number of pickups and `M` number of dropoffs, for cases where a single transporter can have multiple items in its delivery. We don't have that on our roadmap currently because none of our customers have requested it yet, but feel free to submit a PR to add such a task request message.

For the sake of backwards compatibility, I might suggest creating a new message definition for it rather than modifying `Delivery.msg`. Maybe it could be called `MultiDelivery.msg`.

**Comment by Briancbn** [comment]
Hi we are also interested in the support for Delivery with multiple dropoff point, since there aren't any plans yet, maybe we can work on this together.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
