### ISSUE TITLE
question on using fleet adapter #2

### ISSUE THREAD

**Issue by cwrx777** [osrf/rmf_core#171]
For example, there is a numbers of AMRs of the same model (e.g MiR 100). 
Fleet #1 - a fleet of MiR100s is used to transport medicine carts between location A and B.
Fleet #2 - a fleet of MiR100s is used to transport laundry carts between location C and D.
AMRs from Fleet#1 do not share path with Fleet #2.

what is the boundary of a fleet adapter? is it on AMR model level or fleet-level as described in the above example?

**Comment by mxgrey** [comment]
There aren't hard boundaries for the scope of a fleet adapter. A single "fleet adapter" node is allowed to control all the fleets in a deployment, and there may even be some advantages in doing so, since it would significantly reduce the latency of the traffic negotiation process between the different fleets.

The real constraints that will determine the boundaries of a fleet adapter are the practical constraints of system integration. For example:

* If your deployment involves two different robot vendors and each one has a closed-source proprietary API that needs to be used by their fleet adapters, will your NDA with the vendor even **allow** you to use both APIs in one node?
* If you've already deployed a fleet in a facility, but now you need to add a new one, should you just add a new node for this new fleet, or should you temporarily halt the operations to update the existing node with the new fleet information? Or should you design your fleet adapter node so that you can dynamically add new fleet information live while it's still running?

In the `rmf_fleet_adapter` API you can see the constraints of the [`Adapter::add_fleet` function](https://github.com/osrf/rmf_core/blob/727048469f9ce14d6e76628dec96a84ca1ce99f9/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/Adapter.hpp#L97-L100) are:
* All the agents must share the same "fleet name"
* All the agents must share the same `VehicleTraits`
* All the agents must use the same navigation graph

The first constraint is just for convenience, but the second two constraints are for performance reasons. Internally the traffic planner of RMF does some caching, and that cache can be shared between all agents that have the same traits and navigation graph. Each "fleet" (as defined by the `FleetUpdateHandle` object) just has one cache, which cuts down on RAM usage compared to every vehicle having its own independent cache. Note that it's perfectly acceptable to create multiple `FleetUpdateHandle` objects that use the same `fleet_name` value while having different `traits` and `navigation_graph` values. That may be useful if you want to use one "fleet name" to refer to robots that have varying traits or navigation graphs.

But one "adapter" can have arbitrarily many fleets, and the `Adapter` class is the root of a "fleet adapter" node.

So, to address your specific situation, here would be my recommendation:

* Use one "fleet adapter" node
* Use the `Adapter::add_fleet()` once for each navigation graph
* You can give each fleet the same name or a different name; this is entirely up to you

That being said, there may be perfectly valid reasons to not follow that recommendation. Maybe the fleets are supposed to be on different networks? Maybe there's some reason the fleet adapters should run on different servers? So there would be absolutely nothing wrong with using a setup that's completely different than I recommended.

**Comment by cwrx777** [comment]
@mxgrey 
Consider there are two MiR100 fleets.
1st fleet is an MiR100 with perrmanently attached storage (click [here](https://www.mobile-industrial-robots.com/media/4104/soenderborg-hospital_009_small.jpg))
2nd  fleet is an MiR100 with an adapter (top module) that can latch on a cart base (click [here ] to view (https://www.mobile-industrial-robots.com/media/10949/s-cart300-270a9000-with-mir250-and-mir-shelf-carrier-4.jpg))

Workflow for 1st fleet probably it's just to go from one place to another, with some kind of authentication to allow user to open the storage. 

Workflow for 2nd fleet is probably, that user need to place a cart at a staging location and the cart must be placed with the correct orientation(i.e. North South vs East West), and as part of the integration, some sensors are used.  
assuming after a task is assigned to AMR to delivery a cart ID from a pickup location to a drop-off location, after the task is assigned, someone accidentally move the cart. When the AMR reach the pickup location, AMR performs checking if the cart (and the correct cart ID) is present at the pickup location.
at the drop off location, in the event that the drop off location is occupied, the AMR will need to wait for sometimes, sound alert, wait again, and eventually leave the payload (ie. job completion, but with exception).

Questions.
1. Do we need to create two fleet adapters, one for each fleet?
2. is the detailed logic (eg action to pickup and drop off (moving the actuator of the top module), perform checking , retries, play sound) supposed to be implemented in the fleet adapter layer? where in fleet adapter is the place to do this?
3. in terms of the data flow for task assignment, is it correct to say that the task is assigned to a fleet. but fleet adapter will assign to the most suitable AMR within its fleet?

**Comment by mxgrey** [comment]
> Do we need to create two fleet adapters, one for each fleet?

This is up to you, as either option will work. I'd probably recommend implementing them as separate adapters, though, since the logic sounds significantly different for each.

> is the detailed logic (eg action to pickup and drop off (moving the actuator of the top module), perform checking , retries, play sound) supposed to be implemented in the fleet adapter layer? where in fleet adapter is the place to do this?

If this needs to be developed immediately, I think the most feasible approach would be to fork `rmf_core` and tweak some of the logic in the [`make_delivery(~)`](https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/src/rmf_fleet_adapter/tasks/Delivery.cpp) function by adding some custom [phases](https://github.com/osrf/rmf_core/tree/master/rmf_fleet_adapter/src/rmf_fleet_adapter/phases) to it. Hopefully the amount of effort required to do this fork will be relatively small compared to the effort of developing 100% of the task management logic yourself.

I need to caution, though, that these internal implementations (i.e. anything inside of `src` instead of `include`) are not considered stable and are subject to completely change between different version releases. We're currently working on a more publicly exposed API for task planning and task management, but it won't be ready until our December 2020 release at the earliest. That upcoming library will be largely inspired by the existing implementation that I pointed you to, so forking that and familiarizing yourself with it now may still be a valuable exercise for using the official API later when it's ready, even if the work you do with it right now won't be perfectly compatible with the official version that gets released later.

> in terms of the data flow for task assignment, is it correct to say that the task is assigned to a fleet. but fleet adapter will assign to the most suitable AMR within its fleet?

This is accurate. We're working on formalizing this process right now with a "task bidding" system that will assign the task to the fleet that can offer the best bid for completing it.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
