### ISSUE TITLE
Lift integration - how does fleet adapter knows if lift is ready to board

### ISSUE THREAD

**Issue by imdalaf** [osrf/rmf_core#187]
As i went through the documentation in https://osrf.github.io/ros2multirobotbook/integration_lifts.html , i realized that the fleet adapter does not receive any status update about the lift. In that case, how does the fleet knows if the lift has reached the level which the robot called the lift to? And whether the lift door is open or not?

**Comment by mxgrey** [comment]
The page you linked to is targeted at readers who want to integrate their lift, not readers who want to integrate their fleet.

The full control fleet adapter library does take care of subscribing to the lift state topic. Other fleet adapter categories need to take care of lift integration on the user side.

**Comment by imdalaf** [comment]
Thanks @mxgrey 

i have looked at the code and have generate this impression that the GoToPlace class will generate all the actions needed to get the robot to move from start to destination point and if there is any actions such as calling the lift, GoToPlace::Active::execute_plan will generate all the actions to be executed. This function is also the place to define the new alternate plan if there is failure or exceptional (e.g. lift in emergency mode) flow. Is this correct? If not, how do we define new plan for robot to move to a specific location if there is failure or exceptional event happening?

In the GoToPlace::Active::execute_plan function, the EventPhaseFactory seems to be executing event for lift at the level where it distinguish the lift move, lift door open and lift door close operations. But in the LiftRequest.cpp and LiftRequest message, these operations are defined in the same operation (i.e.: the same message is used to ask lift to move to a destination level and have the door open). In the EventPhaseFactory class, the body of Lift Door Close and Lift Move function are not stated as not supported yet, is it because we are expecting to execute only the LiftDoorOpen operation instead of having to trigger LiftDoorClose, LiftMove and LiftDoorOpen operations? This tallies with the one message defines all operation formatin LiftRequest message?

**Comment by mxgrey** [comment]
> GoToPlace class will generate all the actions needed to get the robot to move from start to destination point and if there is any actions such as calling the lift, GoToPlace::Active::execute_plan will generate all the actions to be executed

This is accurate, although in the `rmf_fleet_adapter` we call the actions "phases".

> This function is also the place to define the new alternate plan if there is failure or exceptional (e.g. lift in emergency mode) flow. Is this correct?

Are you asking about modifying the source code of `GoToPlace`? If so, I think I'll need you to elaborate on what kind of changes you have in mind.

> If not, how do we define new plan for robot to move to a specific location if there is failure or exceptional event happening?

I think there is a lot of room for discussion on this, and I may need you to elaborate on what kind of failures and what kind of exceptions.

Hardware failures will ultimately require physical human intervention, so at that point, I believe the robot's task should be canceled and reassigned (this is currently a WIP). Are there other "exceptions" you have in mind?

The `rmf_fleet_adapter::agv::RobotUpdateHandle` class has an function called [`interrupted()`](https://github.com/osrf/rmf_core/blob/42ba1f8173b96e24f40eb52280b47ba088c9b7e0/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/RobotUpdateHandle.hpp#L40-L44) which allows the fleet adapter to ask for a new plan to be generated. In my mind, the best way to deal with exceptions is:

1. Provide the `GoToPlace` planner with enough information so that it can find a plan that deals with whatever exceptional situation has happened.
2. Trigger the interrupt to generate and receive a new plan.

>  EventPhaseFactory seems to be executing event for lift at the level where it distinguish the lift move, lift door open and lift door close operations

The `EventPhaseFactory` is a factory that produces phases for all these different events. The phases don't get executed by the factory; they get executed later by the [`GoToPlace::Active::_subtasks`](https://github.com/osrf/rmf_core/blob/42ba1f8173b96e24f40eb52280b47ba088c9b7e0/rmf_fleet_adapter/src/rmf_fleet_adapter/phases/GoToPlace.hpp#L84) phase manager.

> the body of Lift Door Close and Lift Move function are not stated as not supported yet

Are you looking at the latest `master` branch? The implementations for the different lift events were update in September. The `LiftDoorClose` event has been replaced with `LiftSessionEnd`.

> we are expecting to execute only the LiftDoorOpen operation instead of having to trigger LiftDoorClose, LiftMove and LiftDoorOpen operations?

In the latest version of the fleet and lift adapters, we have a "session locking" protocol to enforce that only one robot can use a lift at a time. Now there are four important events:

1. `LiftSessionBegin`: Begins a session with the lift and asks the lift to move to the pickup floor and open its doors.
2. `LiftMove`: Asks the lift to move to the destination floor.
3. `LiftDoorOpen`: Asks the lift to open its doors at the destination floor.
4. `LiftSessionEnd`: Tells the lift that the session is finished.

The `EventPhaseFactory` creates a "task phase" for each of these events. Each "task phase" will publish relevant lift request messages to trigger the desired behavior from the lift adapters, and each "task phase" will also subscribe to lift state messages to monitor the progress of the lift and ensure that the relevant lift request is being handled.

> This tallies with the one message defines all operation formatin LiftRequest message?

Right, all the different operations that a lift can be asked to perform are encapsulated by the `LiftRequest` message. So the different lift phases just fill out their own lift request messages according to what the phase needs to have happen.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
