### ISSUE TITLE
how to set the starting motion time for individual robot?

### ISSUE THREAD

**Issue by Jason-Zhou1** [osrf/rmf_core#195]
Hi all,
I want to do a simulation about 2 robots: magni1 and magni2. I want magni2 to start motion 10 seconds later than magni1.
Anyone can help me in this issue?

**Comment by mxgrey** [comment]
This question/issue might be better suited for the [`rmf_demos`](https://github.com/osrf/rmf_demos) repo.

That repo provides a [`delayed_request_loop`](https://github.com/osrf/rmf_demos/blob/master/rmf_demo_tasks/rmf_demo_tasks/delayed_request_loop.py) script which you can use [from a launch script](https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/triple_H/the_pedigree.launch.xml#L5) to give a rough timing to the robot motion start times.

This isn't meant to be a robust way of scheduling tasks, but it may be useful for demo and experimental purposes while we currently work on more rigorous task scheduling features.

**Comment by Jason-Zhou1** [comment]
Hi mxgrey,
 I want to simulate an individual robot with velocity different from the default one, say, 1.0m/s. I set the velocity in the demos/launch/include/office/office_loop.launch.xml
<launch>
……
   <executable cmd="ros2 run rmf_demo_tasks request_loop -s hardware_2 -f coe -r tinyRobot -v 1.0 -n 2" output="both"/>
……
</launch>
Next, I add codes about the argument of velocity in rmf_demos/rmf_demos_tasks/rmf_demos_tasks/request_loop.py:
……
   (Ln20) parse.add_argument(‘-v’, ‘- - linear_velocity’, help=’linear velocity of robot’, type =double, default=0.5)
……
   (Ln38) request.linerar_velocity=args.linear_velocity
……

Then, I add the code in the last line of rmf_core/rmf_task_msg/msg/Loop.msg:
……
   double linear_velocity

Now, I have a question to inquire you:
How can I pass the value of velocity to the individual robot in the rmf_core or fleet_adapter code?
Thanks!

**Comment by mxgrey** [comment]
You're talking about completely changing the public API of `rmf_fleet_adapter` in a way that I don't think is sensible.

I don't believe a task request should specify the velocity that a robot uses. A robot's operational velocity is typically determined by the physical capabilities of the robot platform. It's not something that a human user (which is where a task request comes from) should be allowed to fiddle with in my opinion.

The way to change a robot's operational velocity for a demo involves two steps:

1. Modify the [`nominal_drive_speed`](https://github.com/osrf/rmf_assets/blob/d2c25c8882d9f5583213350e7f033f4ab37152ee/models/Magni/model.sdf#L7) value of the model you want to change, or create a new model with the `nominal_drive_speed` value that you want it to have.
2. Modify the [`linear_velocity`](https://github.com/osrf/rmf_demos/blob/09f25a0c850d9efa1418236b31e09b23347b3ea6/demos/launch/include/adapters/tinyRobot_adapter.launch.xml#L20) value in the launch file for the fleet adapter of the robot fleet you're using, or create a new fleet adapter launch file with the `linear_velocity` value that you want it to have.

Now launch the simulation with the modified (or newly created) model and fleet adapter launch file.

**Comment by Jason-Zhou1** [comment]
Hi mxgrey,
I have changed the values of linear velocity in both sides(nominal_drive_speed&linear_velocity), but the actual speed does not change in the simulation. Even when I change the velocity to 0, the robot can still move in normal speed.

**Comment by mxgrey** [comment]
Sorry, it looks like I linked you to a deprecated repo.

If you want to modify the `nominal_drive_speed` of the existing model in the office, you need to change it [here](https://github.com/osrf/rmf_demos/blob/8e7b734f3961fdb71fa1d896ed0ecc3a96c41870/rmf_demo_assets/models/TinyRobot/model.sdf#L7).

I just tested out setting that value to zero, and the robot is no longer able to drive forward (but it can still turn in place).

One thing I should note: Reducing the nominal drive speed in simulation should be fine, but using a higher speed (like the 1.0 that you've mentioned) might not actually work well because the wheels might start slipping. You can fix the slipping by tuning various simulation parameters like friction coefficients and the `kp` & `kd` values for ODE, but this requires either a lot of knowledge about physics simulation or a lot of patience. You can certainly try using a higher value, but don't be surprised if you find the robot slipping.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
