### ISSUE TITLE
Question on RobotState msg

### ISSUE THREAD

**Issue by zach-goh** [osrf/rmf_core#206]
When creating a fleet adapter for a custom robot fleet which supplies RobotState messages, is it necessary to supply the last parameter in the msg `Location[] path`?  Other RobotState parameters will be supplied like `battery percent` except for the `path` array whose elements will be all 0, would such messages still work or will it cause traffic management issues?

**Comment by mxgrey** [comment]
The `RobotState` API is considered deprecated. The recommended way to integrate a full control category robot is to use [the C++ API](https://osrf.github.io/ros2multirobotbook/integration_fleets.html#c-api).

But if you decide to use the `rmf_fleet_msgs` API, then you do need to provide the `path` field, or else, like you inferred, there will be traffic management issues because RMF won't know where your robot is trying to go.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
