### ISSUE TITLE
questions about the detect_invasion() function in DetectConflict.cpp

### ISSUE THREAD

**Issue by Jason-Zhou1** [osrf/rmf_core#220]
Hi all,
I have some questions about how to understand the detect_invasion() function in the "DetectConflict.cpp" file:
https://github.com/osrf/rmf_core/blob/3f20335be09823c873eb44bb669fa003555a2b9a/rmf_traffic/src/rmf_traffic/DetectConflict.cpp#L474-L579
1. In L552-556, my understanding is spline_a will stop there when it finishes earlier than spline_b, but why it will still execute code "++a_it;" ? What's the shape of spline_a then?
2. In L519, what's the shape of bound_a? This may be related to the shape of spline_a. Is spline_s a slice trajectory or the whole spline from a_it to a_end?
Thank you!

**Comment by mxgrey** [comment]
> In L552-556, my understanding is spline_a will stop there when it finishes earlier than spline_b

A trajectory is a piecewise cubic spline. That means one trajectory contains `N-1` splines where `N` is the number of waypoints. That condition checks if `spline_a` has reached its end and moves on to the next spline of `trajectory_a` if it has.

Note that `trajectory_a` and `trajectory_b` may have different timings for their splines, so a single spline from one trajectory may overlap with multiple splines from the other trajectory.

> In L519, what's the shape of bound_a? This may be related to the shape of spline_a.

If you look at the implementation of `get_bounding_profile(~)`, you should see that it's a very simple bounding box of the spline's extrema, inflated by the "characteristic length" (length of the shape's furthest point from its center) of the footprint or vicinity.

> Is spline_s a slice trajectory or the whole spline from a_it to a_end?

It's a "slice" of `trajectory_a`. More specifically, it's the spline that connects exactly two of the trajectory's waypoints.

**Comment by Jason-Zhou1** [comment]
Hi mxgrey,
Thanks a lot for your answer! So in case when robot a finishes but robot b has not finished its travel task, "++a_it;" will make robot a standby at a_end and wait for robot b to continue its travel until b_end. Am I right?

**Comment by mxgrey** [comment]
I'll answer both versions of the questions that you asked since they come across as two different (and both relevant) questions to me.

> So in case when robot a finishes but robot b has not finished its travel task, "++a_it;" will make robot a standby at a_end and wait for robot b to continue its travel until b_end. Am I right?

No, the robot will not stand and wait; it will simply vanish from existence from the perspective of `trajectory_b`. If a robot intends to stop and wait at a location, then the trajectory **needs** to express that, or else the conflict will not be detected.

This might sound like unintuitive behavior, but there are several motivations for it. The most important motivation is that a robot may need to move from one floor to another. Since these trajectories are 2D trajectories encapsulated between different floors, a robot's trajectory will need to disappear from one floor and appear on another floor when moving between floors (e.g. using a lift or going up a ramp. There would be bugs in the conflict detection for multi-floor itineraries if we assume that a robot permanently sits where its trajectory ends.

> So in case when robot a finishes but robot b has not finished its travel task in spline_a, "++a_it;" will make robot a moves to next spline_a of trajectory_a. Here ++a_it is actually equivalent to a_end. Am I right?

`a_end` is a [one-past-the-end](https://en.cppreference.com/w/cpp/iterator/end) iterator. It's a sentinel value that just tells you that you've run out of elements to look at. It does not represent an actual waypoint or spline. When `a_it` reaches the value of `a_end`, the loop will terminate.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
