### ISSUE TITLE
about struct: internal::planning::DifferentialDriveExpander

### ISSUE THREAD

**Issue by Jason-Zhou1** [osrf/rmf_core#225]
Hi all,
May i know who can help me understand the above struct? It's in:
rmf_traffic/agv/internal_planning.cpp#L663-1726.
It seems to do some search work, but i cannot understand what it really doing. Is it related to the trajectory planning?
Any tutorials about this struct is much appreciated.

**Comment by mxgrey** [comment]
Since the class is inside the `src/` folder, it's an implementation detail. By design, it's not something that you as a user have a need to understand. It's not worth documenting or explaining since we may (and indeed have plans to) completely rewrite it at any time.

If you don't understand this class, then I recommend ignoring it and focusing on understanding the [API](https://github.com/osrf/rmf_core/blob/master/rmf_traffic/include/rmf_traffic/agv/Planner.hpp#L38) which is specifically meant to be understandable for users. If you have questions about the API (e.g. how it works or how to use it) that would be a more relevant discussion.
