### ISSUE TITLE
Questions on integration diagram and HA

### ISSUE THREAD

**Issue by cwrx777** [osrf/rmf_core#75]
Hi,

I am trying to understand the components of rmf_core by comparing rmf_core_integration_diagram.png and the packages inside rmf_core. 

I notice that the following are implemented as Nodes:
1. lift_supervisor (package: rmf_fleet_adapter)
2. door_supervisor (package: rmf_fleet_adapter)
3. robot_state_aggregator (package: rmf_fleet_adapter)
4. rmf_traffic_schedule (package: rmf_traffic_ros2)
5. task_aggregator (package: rmf_fleet_adapter)
and there are two execution mode (both of which are FleetAdapterNode)
1. full_control (package: rmf_fleet_adapter)
2. read_only (package: rmf_fleet_adapter)

Questions:
1. Are the above first 5 nodes part actually part of rmf_core in the diagram?
2. is FleetAdapterNode the fleet adapters in the diagram?
3. what is a  schedule in rmf_traffic_schedule?
4. How do we feed a schedule into the scheduler? 

High Availability
1. For high availability, is it recommended in running multiple instances (e.g. VM) which are concurrently running the same set of rmf_core and fleet adapter nodes?
in the event there is VM failure of the VM running e.g. scheduler node, how would another scheduler node (in another VM) continue the work of the dead scheduler node?

Networking
1. Can ROS2 nodes communicate between VM in different networks (e.g. one in an institution, one in a remote data center)?

**Comment by mxgrey** [comment]
The current implementation that you see in the code base is an initial proof of concept that was contractually required by December of 2019. Right now we're working on a complete overhaul of this implementation, so I don't recommend being too concerned about the current implementation details. Even the overview diagram is tentative, although the high level overview of the design is rapidly converging.

Many of the nodes that you listed were designed specifically for a December 2019 proof-of-concept demonstration deliverable and will not be part of the final version of RoMi-H. Here's a breakdown of what our current intentions are:

* There will be some form of schedule node, although it will be implemented very differently than the current one.
* There will not be any `rmf_fleet_adapter/full_control` or `rmf_fleet_adapter/read_only` nodes. Instead we intend to have `rmf_core` provide C++ and Python libraries to help robot vendors integrate their custom/proprietary APIs into the RoMi-H scheduling system. The APIs for those libraries are currently being determined.
* Nodes like `task_aggregator`, `lift_supervisor`, and `door_supervisor` are highly dependent on the rules of whatever facility RoMi-H is being deployed in. These nodes will probably be removed from `rmf_core`, perhaps replaced with utility libraries that would help system integrators to easily develop similar nodes for their deployments as necessary.

> what is a schedule in rmf_traffic_schedule?

The schedule is a centralized database of all the intended robot traffic trajectories in a facility. Note that it's the **intended** trajectories, so it's looking into the future. The job of the schedule is to identify conflicts in the intentions of the different robot fleets and notify the fleets when a conflict is noticed. It will also facilitate a procedure for the fleets to automatically resolve their conflict. If no resolution is found in a reasonable time, the conflict may be escalated to the attention of a human operator.

> How do we feed a schedule into the scheduler?

A new API for this is being worked on right now and should be released soon. (I'm aiming for the end of this week if I don't have too many interruptions.)

> For high availability

I can't make a strong recommendation for this right now since it's a subject of ongoing research. But I can share at least some plans that we have in mind right now: For the schedule, we intend to do regular backups to an on-disk SQL database as well as have mirrors on remote machines listening to the full schedule. If the current schedule server goes down, one of the remote mirrors would be promoted to the official schedule server.

For the components that are supplied by system integrators (e.g. the fleet adapter that talks to the schedule) the strategy for high availability will be determined by the system integrator, and it will most likely depend on how the endpoint system (e.g. robot fleet manager) works. We'll try to design the `rmf_core` integration libraries to have utilities for making it easy for the system integrators to failover on their communications with the schedule, but that may require some engagement with the system integrators and vendors to understand how their systems would want to failover.

> Can ROS2 nodes communicate between VM in different networks (e.g. one in an institution, one in a remote data center)?

I won't pretend to know the answer to this for certain, but I believe this boils down to your DDS and VM configurations. As far as I'm aware, DDS is happy to operate over any network; you just need to make sure your DDS deployment is configured to allow it (e.g. use static discovery to connect the nodes in the institution to the nodes in your remote data center). But whether an institution allows there to be any connection between its internal operations network and your remote data center is something that you'd need to work out with the institution.

**Comment by cwrx777** [comment]
Hi @mxgrey ,

For example, there are multiple fleets that actually can do the same type of task. is there or will there be a layer to manage between fleets (e.g. fleets manager) that will be able to assign the task to the fleet with available AMRs?

**Comment by mxgrey** [comment]
It's not implemented yet, but there's a design worked out for a bidding system where a task request will be converted to a bid request. The bid request will be sent to each fleet adapter, and each fleet adapter that can perform the task will report its best estimate for how soon it would be able to have the task finished. The fleet adapter that offers the lowest bid will be assigned the task.

The API and implementation for this is on the backburner right now as we finalize some of the more critical components of RoMi-H.

**Comment by cwrx777** [comment]
Hi @mxgrey , 
In a scenario that a robot needs to open a door or request for the lift, who has the knowledge that the robot that at some point it will need to get the door opened? (is it the robot or RoMi-H or both)?
and when the robot is getting closer to the door, is the request to open the door coming from (or published by) the robot or RoMi-H?

**Comment by mxgrey** [comment]
The responsibility of knowing when a door needs to be opened and then sending the command to open it belongs to the "fleet adapter". The current implementation can be found [here](https://github.com/osrf/rmf_core/blob/50db2ef506f46e6ea56cb825d2baa75eb75697fd/rmf_fleet_adapter/src/full_control/MoveAction.cpp#L996-L1041). That specific implementation will be undergoing some huge refactoring over the next few weeks, but the basic design will remain exactly how it already is:

* The fleet adapter keeps track of the robot's progress
* When the robot needs to go through a door, the fleet adapter will recognize this
* The fleet adapter will send a signal to the door to open
* Once the door is open, the fleet adapter will command the robot to proceed
* Once the robot is through the door, the fleet adapter will command the robot wait until the door is closed
* The fleet adapter will command the door to close
* Once the door is closed, the fleet adapter will command the robot to proceed

The way a fleet adapter knows about the doors is by parsing the navigation graph that is provided to it. The navigation graph is a required parameter for the `full_control` type of fleet adapter. `rmf_demos` [shows an example](https://github.com/osrf/rmf_demos/blob/2d7b9c7c75211b89b91977e5d1a66f440cc5df95/demos/launch/office.launch.xml#L37) of providing a navigation graph to the fleet adapter.

The recommended way to construct a navigation graph is to use the [`traffic-editor`](https://github.com/osrf/traffic_editor) tool. The `rmf_demos` repos shows some [examples of `traffic-editor` project files](https://github.com/osrf/rmf_demos/tree/2d7b9c7c75211b89b91977e5d1a66f440cc5df95/rmf_demo_maps/maps).

However, it's entirely possible to construct your own navigation graphs. They use a very simple yaml format. We don't have documentation for the format specs yet, but you can see exactly how they get parsed [here](https://github.com/osrf/rmf_core/blob/50db2ef506f46e6ea56cb825d2baa75eb75697fd/rmf_fleet_adapter/src/rmf_fleet_adapter/ParseGraph.cpp).
